### ISSUE TITLE
居然没有人提Issues？我来提一个

### ISSUE THREAD

**Issue by guozhiqiang123** [AllenXiao1994/OkSimple#1]
我认为Okgo最优秀的地方在于对缓存的设计，这是最应该借鉴的。

**Comment by GateOfTruth** [comment]
然而如果你仔细分析okgo的源码和对okhttp的缓存比较熟悉的话，你会发现okgo很多时候是把okhttp已有的东西重新弄一遍。okhttp本身是有缓存机制的，可以参考[这篇文章](https://www.jianshu.com/p/ecf64bda343e)

**Comment by guozhiqiang123** [comment]
okhttp虽然自带了缓存，但是使用并不灵活，比如需要服务器端来进行配合，但是遇到不好合作的后端或者比较忙的后端，这些需求就不容易落地；另外一个我认为自带缓存不好使的是业务场景太单一，比如在首屏数据量比较大，我们往往希望先从本地拿到数据渲染界面，然后并发从服务器端拉取数据，用Diff进行差异渲染，这种需求也是不能满足的；再者没有网络状态下强制走缓存，也需要自己自定义拦截器，增加了技术复杂度。我认为一款优秀的网络框架应该是处理好缓存，并且扩展强，满足百分之99的业务场景，虽然Okgo还有很多不如意的地方，但我认为缓存这一块并不是在弄重复的东西，而是对自带缓存的扩展

**Comment by GateOfTruth** [comment]
关于这一块，我和你持不同看法。我是觉得缓存本来在http协议里就有相关规范，后端只需要遵循规范去设计和控制，返回相应的http header就可以了。也就是说，缓存本来就应该是后端控制的。有些事应该前端做，有些事则不应该是前端做。至于没有网络的情况下，强制走缓存，其实也只是几行代码的事，后续我可能会考虑加上

**Comment by guozhiqiang123** [comment]
理论上缓存的确应该后端控制，但是真实的开发环境中确不是每件事都是按规矩来的，如果真那样，很多事反而简单了。只是个人建议！！！

**Comment by GateOfTruth** [comment]
1.2.1新增了没有网络的情况下可以添加force cache，省去了再手动写拦截器的麻烦。缓存这块如果没有bug的话，目前应该不会再做其他改动了。
