### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by AdminQQZ** [AllenXiao1994/OkSimple#2]

**Comment by AdminQQZ** [comment]
把OKGo的所有功能移植过来，然后处理它的问题。就完美了

**Comment by GateOfTruth** [comment]
我设计之初的确有参考okgo，但我并没有打算完全照搬它。不管是设计和编码的思路还是具体功能的实现。我希望oksimple尽可能的保持简洁和扩展性。如果你有好的建议，也欢迎提出。

**Comment by AdminQQZ** [comment]
有一种需求，multipart/form-data 来提交参数和文件。可以实现吗

**Comment by GateOfTruth** [comment]
这个已经实现了吧，目前是可以同时提交参数和文件的。具体可以参考[PostFormActivity](https://github.com/AllenXiao1994/OkSimple/blob/master/app/src/main/java/com/alen/oksimpleutil/PostFormActivity.kt)

**Comment by AdminQQZ** [comment]
嗯，发现okhttp，会把


文字和文件分两部分的content-type来提交。那后台想直接把字符串和文件都用 multipart/form来提交，这样是可以的吗

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AllenXiao1994"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 中午1:22
收件人: "AllenXiao1994/OkSimple"<OkSimple@noreply.github.com&gt;; 
抄送: "867711323"<867711323@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AllenXiao1994/OkSimple] 加油 (#2)




这个已经实现了吧，目前是可以同时提交参数和文件的。具体可以参考PostFormActivity
 
&mdash;

**Comment by GateOfTruth** [comment]
不是很理解你的意思，因为会分成两部分是正常的。multipart/form-data本身就是这样的。它会给每个body分段，但整体依然是表单形式，所以我觉得我这一块应该没什么问题。

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/70208239-ef2d1180-1767-11ea-8e7a-35422720b57f.png)
我想指定字符串也用 multipart/form

**Comment by GateOfTruth** [comment]
emmmm，可是字符串和文件都属于multipart/form-data啊，因为在提交的时候，form-data是作为一个整体提交的，所以他们某种意义上可以说“是”multipart/form-data，而且 multipart/form-data是一种Multipart类型，单独的字符串一般属于text/plain或者text/html这两种mime类型。你没办法也没必要指定字符串是multipart/form-data类型。

**Comment by AdminQQZ** [comment]
后台那个王八蛋，他就要。怎么办，我们吵了2天架了。文件和字符串参数一并上传。用multipart/form-data&nbsp; 我都跟他讲了。文件就是文件，字符串就是字符串
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AllenXiao1994"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 下午2:09
收件人: "AllenXiao1994/OkSimple"<OkSimple@noreply.github.com&gt;; 
抄送: "867711323"<867711323@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AllenXiao1994/OkSimple] 加油 (#2)




emmmm，可是字符串和文件都属于multipart/form-data啊，因为在提交的时候，form-data是作为一个整体提交的，所以他们某种意义上可以说“是”multipart/form-data，而且 multipart/form-data是一种Multipart类型，单独的字符串一般属于text/plain或者text/html这两种mime类型。你没办法也没必要指定字符串是multipart/form-data类型。
 
&mdash;

**Comment by GateOfTruth** [comment]
emmm，你们可以共同参考[这个链接](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types)。我不是很清楚你们后台需要的请求类型是什么样的，如果可以的话，可以把你们需要的类型发给我。如果是我的框架里没有的，我会考虑补全
