### ISSUE TITLE
formBody提交可以吗

### ISSUE THREAD

**Issue by AdminQQZ** [AllenXiao1994/OkSimple#3]
后台需要formBody来提交数据

**Comment by GateOfTruth** [comment]
可以的，可以参考[示例](https://github.com/AllenXiao1994/OkSimple/blob/master/app/src/main/java/com/alen/oksimpleutil/PostFormActivity.kt)，表单提交也就是formbody提交

**Comment by AdminQQZ** [comment]
override fun failure(call: Call, e: Exception) {
                e.printStackTrace()
}
失败，可以加上code 返回吗？ 有些业务，失败后，要进行逻辑判断，在跳转页面。

**Comment by GateOfTruth** [comment]
如果你说的是404,500之类的错误码，是在response里返回。这个回调方法是回调诸如sockettimeout之类的异常错误。和okhttp原有的回调是一样的

**Comment by GateOfTruth** [comment]
我注意到你之前也提过类似的ISSUE，如果对formbody提交还有什么疑问，欢迎加我QQ进行讨论，我在redme更新了我的QQ。
