### ISSUE TITLE
如何提交一个JsonArray的post请求，type org.json.JSONArray cannot be converted to JSONObject

### ISSUE THREAD

**Issue by baolijin** [AllenXiao1994/OkSimple#5]
我想body中提交jsonArry，框架似乎不支持。或者单纯提供一个传String的方法

**Comment by GateOfTruth** [comment]
因为我们公司这边提交数据都是用一个封装好的格式，jsonarray都会放在jsonobject里面，所以没有这个方法。不过确实可以加一个提交jsonarray的方法，这几天有空的话我会加上并发一个版本

**Comment by GateOfTruth** [comment]
3.3.7版本新增了post jsonarray的方法，issue close
